---
version: "3.4"
services:
  sof_wrapper:
    build:
      context: .
    volumes:
      - ./:/opt/app
      # mount host certificates into container
      - /etc/ssl/certs:/etc/ssl/certs:ro
    ports:
      # allow override of published port
      - ${P_PORT:-5000}:5000
    env_file:
      - sof_wrapper.env
